### ISSUE TITLE
Creating a new AuthChannel

### ISSUE THREAD

**Issue by vanessagertman** [alpas/alpas#12]
I am migrating an existing AWS Lambda function to Alpas and I have a question about how I should implement my AuthChannel (since I won't be using Sessions). 

I have this part working so far: 

1. The client making the request sends an encrypted auth token (encrypted with a public key) in the auth header of the request. 
2. The AuthChannel decrypts the auth token using a private key stored on the server (if the token can't be decrypted, I am returning `false` for `check()`)
3. Then, the AuthChannel parses some data out of the token. One of the pieces of data in the auth token is an API key so I check that and if it doesn't match whats in my `env` I return `false` for` check()`. Also, if the format doesn't match what I expected, I return `false` for `check()`) 

The auth token has information that I want the ability to access later on when I am actually handling the request. I don't want to have to decrypt the auth token again in my controllers because it is expensive. I would like to just be able to access this data after parsing it in the AuthChannel. 

Right now, the information I need is a userId and one other id. This almost sounds like a case for creating a new UserProvider but I am not quite sure if that makes sense or not. I don't actually know anything about the users in this application other than a unique id. 

Based on that description, should I be making a UserProvider to save that information or is that weird?
Is there a better place in the call for me to save this information?

**Comment by ashokgelal** [comment]
You could use a `UserProvider` but it is more for mapping a "session" to a user. I'd rather use the `AuthChannel` to hold any state (call it `SessionInfo` or something like that). An `AuthChannel` is [created for every call](https://github.com/alpas/alpas/blob/af2199bb076fcc6bd836126802ac4f3925ed537c/framework/src/main/kotlin/dev/alpas/auth/AuthConfig.kt#L9) so you should feel free to store any state in here.

Later, you can get this auth channel through [HttpCall's  lazy `authChannel` property](https://github.com/alpas/alpas/blob/af2199bb076fcc6bd836126802ac4f3925ed537c/framework/src/main/kotlin/dev/alpas/http/HttpCall.kt#L46), which is basically a singleton. The only downside is you'd have to cast this down to your type and get the information out of it.

In future, I could improve the core by adding a property in `AuthChannel` interface, something like `SessionBag`, to make it easier or add something to `HttpCall` itself.

I hope this was helpful.

**Comment by vanessagertman** [comment]
Thank you very much, that was very helpful! I will try that approach
